// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUWbwDTy1siQvMDfH-y54uKdyfs73HqlI',
    appId: '1:470247889011:android:12a2af612c4bcf8f0ab206',
    messagingSenderId: '470247889011',
    projectId: 'newcurrencycconverter',
    storageBucket: 'newcurrencycconverter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANO6cd_nuykTwAosyonZDJuZhz0W7gnt4',
    appId: '1:470247889011:ios:aef2d1b44cbbe5530ab206',
    messagingSenderId: '470247889011',
    projectId: 'newcurrencycconverter',
    storageBucket: 'newcurrencycconverter.firebasestorage.app',
    androidClientId: '470247889011-aq9o96unmhds5ap74anjrmfjunlddsc1.apps.googleusercontent.com',
    iosClientId: '470247889011-fpec2vgsk67lkhlarlvd64k4afst61gs.apps.googleusercontent.com',
    iosBundleId: 'com.example.currencyConverter',
  );

}